import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillSunFill } from "react-icons/bs";
import { useState } from "react";
import avatar from "../public/avatar.jpg";
import frameworks from "../public/frameworks.png";
import languages from "../public/languages.png";
import tools from "../public/tools.png"
import Image from "next/image";
import NeuroMosaic2 from "../public/NeuroMosaicImage2.png";
import ChirpChat1 from "../public/ChirpChatImage1.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "" : "dark"}>
      <Head>
        <title>Website Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developed by</h1>
            <ul className="flex items-center">
              <li>
                <BsFillSunFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 levitate"
                    href="https://docs.google.com/document/d/1Zx2Vl-wT2s_GotkDOx5A56h9dilaWyWcbTndP5t96Ok/edit?usp=sharing"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Brandon Ding
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Hi, I'm a full stack developer looking for full-time roles! Welcome to my portfolio!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                <a href="https://www.linkedin.com/in/brandon-ding-b965221b1/" target="_blank" rel="noopener noreferrer" className="levitate">
                    <AiFillLinkedin />
                </a>
                <a href="https://github.com/dexon888" target="_blank" rel="noopener noreferrer" className="levitate">
                    <AiFillGithub />
                </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={avatar} alt="" layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Bio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Welcome! I&apos;m Brandon, a passionate grad student currently attending the <span className="text-yellow-500"> Georgia Institute of Technology </span> for <span className="text-teal-500"> computer science </span>. Having served multiple internships and worked as a teaching assistant for multiple courses, I've garnered skills valuable for the tech industry!
              Connect with me on LinkedIn or check out my projects on GitHub.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer a wide range of knowledge from various technologies and frameworks!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={languages} alt="" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Languages
              </h3>
              <p className="py-2">
                Proficient in a diverse array of programming languages
              </p>
              <h4 className="py-4 text-teal-600">Languages I Use</h4>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">C/C++</p>
              <p className="text-gray-800 py-1">C#</p>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">HTML/CSS</p>
              <p className="text-gray-800 py-1">SQL</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={frameworks} alt="" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Frameworks
              </h3>
              <p className="py-2">
                Experienced in leveraging modern frameworks to build dynamic and responsive web applications
              </p>
              <h4 className="py-4 text-teal-600">Frameworks I Use</h4>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Node.js</p>
              <p className="text-gray-800 py-1">Express</p>
              <p className="text-gray-800 py-1">Tensorflow</p>
              <p className="text-gray-800 py-1">Springboot Java</p>
              <p className="text-gray-800 py-1">MongoDB</p>
              <p className="text-gray-800 py-1">MySQL</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={tools} alt="" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Developer Tools
              </h3>
              <p className="py-2">
                Skilled in utilizing a wide range of developer tools
              </p>
              <h4 className="py-4 text-teal-600">Developer Tools I Use</h4>
              <p className="text-gray-800 py-1">Github</p>
              <p className="text-gray-800 py-1">AWS</p>
              <p className="text-gray-800 py-1">Microsoft Azure</p>
              <p className="text-gray-800 py-1">Google Firebase</p>
              <p className="text-gray-800 py-1">Docker</p>
              <p className="text-gray-800 py-1">OpenAI</p>
            </div>
            
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a software developer, I've worked on multiple
              <span className="text-teal-500"> projects. </span>
              Feel free to take a look at any of them here! 
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <a href="https://github.com/dexon888/AI-Notion" target="_blank" rel="noopener noreferrer" className="basis-1/3 flex-1 levitate">
              <div>
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={NeuroMosaic2}
                  alt=""
                />
              </div>
            </a>

            <a href="https://github.com/dexon888/Chatot-Chat-Application" target="_blank" rel="noopener noreferrer" className="basis-1/3 flex-1 levitate">
              <div>
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={ChirpChat1}
                  alt=""
                />
              </div>
            </a>
          </div>
        </section>
      </main>
    </div>
  );
}
